//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemMonitoring
{
    using System;
    using System.Collections.Generic;
    
    public partial class Culture
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Ph { get; set; }
        public string Phosphor { get; set; }
        public string Potassium { get; set; }
        public string Magnesium { get; set; }
        public string Calcium { get; set; }
        public string Humidity { get; set; }
        public string Nitrogen { get; set; }
        public string Temperature { get; set; }
    }
}
