//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemMonitoring
{
    using System;
    using System.Collections.Generic;
    
    public partial class Field
    {
        public int Id { get; set; }
        public string District { get; set; }
        public string Number { get; set; }
        public string Position { get; set; }
    }
}
