//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemMonitoring
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seeding
    {
        public int Id { get; set; }
        public Nullable<int> IdField { get; set; }
        public Nullable<int> IdCulture { get; set; }
        public string Status { get; set; }
        public string Date { get; set; }
    
        public virtual Culture Culture { get; set; }
        public virtual Field Field { get; set; }
    }
}
